### ISSUE TITLE
Réduire la taille des images utilisées

### ISSUE THREAD

**Issue by yanjost** [AlsaceDigitale/www.edgefest.fr#1]
Actuellement certaines des images utilisées sont trop grosses. Il faudrait réduire leur taille à 200-300kb si ça ne gène pas par rapport à l'aspect visuel

**Comment by FriesFlorian** [comment]
outil pratique : https://tinyjpg.com/

**Comment by yanjost** [comment]
@FriesFlorian Une suggestion sur la taille des images à avoir ?

**Comment by FriesFlorian** [comment]
Réduire la résolution des images à la taille maximale auquel elle est
utilisé sur le site puis la compresser un maximum sans la faire perdre en
qualité.

**Comment by FriesFlorian** [comment]
Hadrien a fait un nettoyage des images non utilisées sur le repo, j'ai réduit la taille de toutes les autres qui étaient trop importantes.
